# Generated by Django 5.1.5 on 2025-04-07 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0005_alter_chatroom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bubble.chatroom'),
        ),
    ]
