# Generated by Django 5.1.5 on 2025-04-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0007_alter_chatroom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/room'),
        ),
    ]
